INSERT INTO `usuariosys` (`idUsuario`, `nomyap`, `usuario`, `contraseña`, `dni`, `telefono`, `direccion`, `email`, `idLocalidad`, `tipoUsuario`) VALUES (NULL, 'operador', 'operador', SHA1('operador'), '36737373', '7373737', 'chaco 171', 'operador@gmail.com', '1', 'O');

INSERT INTO `usuariosys` (`idUsuario`, `nomyap`, `usuario`, `contraseña`, `dni`, `telefono`, `direccion`, `email`, `idLocalidad`, `tipoUsuario`) VALUES (NULL, 'admin', 'admin', SHA1('admin'), '28288828', '227227', 'chaco 8282', 'administrador@gmail.com', '1', 'A');

INSERT INTO `usuarioescribano` (`idEscribano`, `nomyap`, `usuario`, `contraseña`, `dni`, `telefono`, `direccion`, `email`, `matricula`, `estadoAprobacion`, `idLocalidad`, `idUsuario`, `motivoRechazo`) VALUES (NULL, 'escribano', 'escribano', SHA1('escribano'), '9282828', '828282', 'Perrando 8182', 'escribano@catastro.com', '373373', 'A', '1', NULL, NULL)




--u573145727_root
--2016sirmiCatastr0